FROM erlang:21

#
# Install additional tooling to help in development of code
#
RUN apt-get -q update \
 && apt-get install -y curl net-tools vim \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
